//OPERATORS AND EXPRESSIONS
console.log("Operators In Java");
let a = 45;
let b = 4;
console.log("The value of a+b is ",a+b);
console.log("The value of a*b is ",a*b);
console.log("The value of a/b is ",a/b);
console.log("The value of a-b is ",a-b);

console.log("The value of a**b is ",a**b);
//A TO THE POWER B

console.log("The value of a%b is ",a%b);
//remainder


//Increment and Decrement Op
console.log("The value of a++ is ",a++); //pehle print fir add
console.log("The value of a is ",a);
console.log("The value of a+b is ",a--); //pehle print fir minus
console.log("The value of ++a is ",++a);//pehle add fir print
console.log("The value of --a is ",--a);//pehle minus fir print

